databaseType = "PostgreSql"
id = "9c7ee88d-98c0-429c-9540-d265e026de3e"
name = "pwap-db"

[flywayDesktop]
developmentEnvironment = "development"
shadowEnvironment = "shadow"
schemaModel = "./schema-model"

[flywayDesktop.generate]
undoScripts = true

[redgateCompare]
filterFile = "filter.rgf"

[flyway]
locations = [ "filesystem:migrations" ]
baselineVersion = "V1__example.sql"
baselineOnMigrate = true

[environments.development]
url = "jdbc:postgresql://localhost:5432/postgres"
schemas = [ "public" ]
displayName = "Development database"

[environments.shadow]
url = "jdbc:postgresql://localhost:5432/postgres"
schemas = [ "public" ]
displayName = "Shadow database"
provisioner = "clean"