name: Deployment

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
    
env:
  ACTIONS_RUNNER_DEBUG: true
        
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    env:
      flywayToken: ${{ secrets.FLYWAY_TOKEN }}
      flywayEnvironment: ${{ secrets.FLYWAY_ENVIRONMENT }}
      flywayPublishResult: ${{ secrets.FLYWAY_PUBLISH_RESULT }}
      flywayCheckDrift: ${{ secrets.FLYWAY_CHECK_DRIFT_ON_MIGRATE }}
      flywayEmail: ${{ secrets.FLYWAY_EMAIL }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Migrate Development DB
        uses: red-gate/FlywayGitHubAction@main
        with:
          url: ${{ secrets.DATABASE_URL }}
          user: ${{ secrets.DATABASE_USER }}
          password: ${{ secrets.DATABASE_PASSWORD }}
          locations: filesystem:./sql